### PR TITLE
Support intellij

### PR DESCRIPTION
**Pull request by pauldraper**
Currently requires using scala_import/scala_import_external which provide IntellijInfo, for transitivity. (Also in Bazel 0.12.0, java_import breaks labels.)

If we don't need transitivity, other imports are fine. IMO, an IDE should query for transitive deps anyway.

### CODE REVIEW

**Comment by pauldraper** [comment]
@jjudd

**Comment by jjudd** [comment]
Awesome. I'll take a look when I have a moment, please don't wait for me before merging if you want to get this in.

**Comment by pauldraper** [comment]
Yeah, mentioned you as an FYI, since this was based on your work.

**Comment by joprice** [comment]
Should this work for the base scala dependencies provided by these rules? I can jump to source on everything installed vis rules_jvm_external's `maven_install`, but not for scala standard library imports, which are all red.

**Pull request merged**
